SHELL = /bin/sh
include ../../make.CHOICES

LIBDIR = ../../$(LIB_REL_DIR)
SRCDIR = ..
CHKDIR = ../..

include $(SRCDIR)/make.$(PLAT)

all: mlfg.o

mlfg.o:  $(SRCDIR)/sprng.h mlfg.cpp mlfg.h \
	$(SRCDIR)/memory.h $(SRCDIR)/store.h
	$(CC) -c $(CFLAGS) $(INLINEOPT) mlfg.cpp -I$(SRCDIR)

clean:
	rm -f *.o

realclean:
	rm -f *.o *~ core a.out
